### ISSUE TITLE
Suppress `chatty` printing in monoalphabetic tests using Suppressor.jl?

### ISSUE THREAD

**Issue by jakewilliami** [Smaug123/ClassicalCiphers.jl#31]
This would be a test-specific dependency.  

Due to code coverage, we needed to add a `chatty` kwarg to one of the monoalphabetic tests.  I do not think it ideal to print the output of that in the tests (we only really care about the total outcome for testing; i.e., did it work?).  We could use [Suppressor.jl](https://github.com/JuliaIO/Suppressor.jl) for this, as a test-specific dependency.  Alternatively, we could alter the `crack_monoalphabetic` function to take in an input that is an `IOStream` and default to `stdout`.

Which would you prefer @Smaug123?  Either way I can sort it out, just let me know

**Comment by Smaug123** [comment]
I don't really know what Julia's norms are here, but I'd personally prefer to take an IOStream (but then I write enterprise software these days :P ) I don't have a strong view though, so if you prefer one or the other then feel free.

**Comment by jakewilliami** [comment]
That's my preference too, so I'll go ahead and implement that quickly!
